name = "omove-store"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "20"
GITHUB_OWNER = "ashikdaspc-star"
GITHUB_REPO = "omove-store"
GITHUB_BRANCH = "main"

[[d1_databases]]
binding = "DB"
database_name = "omove-store-db"
database_id = "464d8440-c3f3-4230-9b6b-74437a47c1d8"


